[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spotisonic"
version = "0.1.0"
description = "An app geared towards music discovery through Spotify track previews."
authors = [
    { name = "LostInLunacy", email = "callum.heavens96@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }  # Add a LICENSE file!

# Will add dependencies as I go...